config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  resources :artists, only: [:index] do
#    resources :albums, only: [:index] do
#      resources :songs, only: [:index] do
#      end
#    end
#  end
  get 'artists', to: 'artists#index', as: 'artists'
  get 'artists/:id', to: 'artists#show', as: 'artist'
  root 'artists#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def show
    @artist = Artist.find params[:id]
    @albums = @artist.albums
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<div class="container">
<% @artists.each do |artist| %>
  <div class="frame col-md-3">
    <img src='<%=artist.image_url%>' alt="Artist photo" width="250" height="250"><br>
    <%=artist.name%><br>
    <%=link_to "Ver más", artist_path(artist)%>
  </div>
<%end%>
</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="row well">
    <div class="col-md-8">
      <h1><%=@artist.name%></h1>
    </div>
    <img src='<%=@artist.image_url%>' alt="Artist photo" width="300" height="300"><br>
  </div>
  <div class="row">
    <h3>Albums (<%=@albums.length%>)</h3>
  </div>
<% @albums.each do |album| %>
  <div class="frame col-md-3">
    <img src='<%=album.image_url%>' alt="Album photo" width="250" height="250"><br>
    <%=album.name%><br>
    <%=album.released_at%>
  </div>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spofity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-brand"><%=link_to "Spofity", artists_path%></div>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">My music</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>